### ISSUE TITLE
apply: Creating pipe: Too many open files

### ISSUE THREAD

**Issue by jkitchin** [magit/emacsql#28] opened 2017-01-10 21:06 UTC
I am looping through a lot of files and emacsql calls (thousands) and I get the error above. That makes me think I am leaking file handles in my loops, maybe from opening and closing the connection?

Any hint on where this might be happening?

edit: Hm. Seems to be directory files that are open.

**Comment by skeeto** [comment] 2017-01-10 22:09
The first concern would be: Are you consistently calling emacsql-close
on each handle? Since I'm betting you are, my guess is that the problem
is the way EmacSQL closes SQLite sessions. It sends an EOF to the
subprocess, but the process doesn't actually exit until it processes the
EOF and voluntarily self-terminates. If you're opening and closing
rapidly in a loop, the subprocesses may not have the chance to terminate
before Emacs runs out of file descriptors.

The reason I don't use kill-process or delete-process is that I want the
subprocess to exit gracefully, especially since there's a database
attached to it. That suggests maybe there should be an optional argument
to have emacsql-close abruptly close a database connection.

In your situation, you could use emacsql-process to extract the process
object from the connection and either:

1) Manually kill it with delete-process. I think this will immediately
   recover the file descriptor. However, it won't gracefully shut down
   SQLite.

2) Or, after emacsql-close, call process-accept-output on the process to
   wait until it processes the EOF. This will slow down your loop.

What operating system are you using? I wasn't actually able to reproduce
the problem on Linux (Emacs 24.4), so I can't test these solutions.

**Comment by jkitchin** [comment] 2017-01-11 00:42
I am on macOSX Sierra.

It seems if I run delete-process and then i don't run into the problem as often. This happens probably because I am looping through about 1600 files, and adding hundreds/thousands of rows per file. In one file trying to add 49183 rows (400 at at time) also triggered this error. If I had a small sleep-for delay (0.1), it seems to get past that too.

**Comment by skeeto** [comment] 2017-01-11 01:44
I thought of something else. You can use ATTACH and DETACH to operate on
multiple databases through a single connection. Should be much faster
than creating new connection objects over and over, too. However, you'll
need to bypass the s-expression query compiler to provide your own query
string since you need to pass a filename, which currently won't work
right. For example, these won't quite work:

    [:attach "foo.db" :as foo]
    ;; ...
    [:detach foo]

It's another need for raw string values.

Right now my first idea for raw strings are to signifify it by making it
propertized:

    [:attach #("foo.db") :as foo]

But I haven't found a way to detect it when there are no actual
properties. Another idea is to use the quote operator, so that when it's
applied to a string it isn't printed, but passed raw.

    [:attach '"foo.db" :as foo]

**Comment by skeeto** [comment] 2017-01-11 03:00
With the new raw string support:

    $ sqlite3 /tmp/foo.db
    sqlite> create table t (x);
    sqlite> insert into t values (1), (2), (3);
    sqlite> .quit

~~~el
(let ((db (emacsql-sqlite nil)))
  (emacsql db [:attach $r1 :as foo] "/tmp/foo.db")
  (prog1 (emacsql db [:select x :from t])
    (emacsql db [:detach foo])))

;; => ((1) (2) (3))
~~~

Or (note the quote on the filename string):

~~~el
(let ((db (emacsql-sqlite nil)))
  (emacsql db [:attach '"/tmp/foo.db" :as foo])
  (prog1 (emacsql db [:select x :from t])
    (emacsql db [:detach foo])))

;; => ((1) (2) (3))
~~~

**Closed** 2022-09-15 19:06 UTC
